name: Format

on:
  push:
    paths:
      - '**.go'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check formatting
      run: if [[ -n "$(gofmt -l .)" ]]; then exit 1; fi
